%{
(* Builds nodes of OCaml's own [Parsetree], not a custom AST: this parser
   produces real [Parsetree.structure] / [Parsetree.expression] values, which
   is what lets the rest of the pipeline hand them straight to the OCaml
   type-checker (compiler-libs' [Typemod]/[Typecore]) and pretty-printer
   ([Pprintast]). *)
open Parsetree
open Asttypes

exception MyError of string

let operator_cnt = ref 0
let operator_tbl = Hashtbl.create 97

let trait_def = Hashtbl.create 97

(* Per trait (without a type constructor): its method signatures, as
   declared, for each impl to build the exact signature it's checked
   against (see the IMPL rule). *)
let trait_vals : (string, Parsetree.signature_item list) Hashtbl.t = Hashtbl.create 97

(* Per trait declaring a type constructor (`type t of 1`): that
   constructor's name and arity. Such a trait's self type is the
   constructor itself, and its other names (e.g. `a`, `b`) are plain type
   variables in its signature rather than abstract types: see [item]'s
   TRAIT rule and [mkctorimpl]. *)
let trait_ctor : (string, string * int) Hashtbl.t = Hashtbl.create 97

(* The type parameters of an [arity]-ary constructor: ['x0; 'x1; ...]. *)
let ctor_params loc arity =
  List.init arity (fun i -> (Ast_helper.Typ.var ~loc (Printf.sprintf "x%d" i), (NoVariance, NoInjectivity)))

(* Per trait method name (e.g. "print", "fold_left", or an operator's
   generated "op___N___"): its full params-then-return type-name chain,
   e.g. ["a"; "a"; "bool"] for `a -> a -> bool` (same convention as
   bin/main.ml's [collect_trait_methods]: "_" marks a non-bare-name
   position, such as a function type like `(a -> unit)`). Filled in by
   [atom_body_trait_def] when a trait declares the method; consulted by
   [annotate_self_params] to know *which* of an impl's own parameters
   actually are the self type (and so need annotating) -- not every
   parameter is, e.g. `foldable`'s `fold_left`'s `acc` and callback aren't. *)
let method_sig_tbl : (string, string list) Hashtbl.t = Hashtbl.create 97

let rec trait_type_names (ty : core_type) : string list =
  match ty.ptyp_desc with
  | Ptyp_arrow (_, t1, t2) ->
    let n =
      match t1.ptyp_desc with
      | Ptyp_constr ({ txt = Longident.Lident n; _ }, []) -> n
      | _ -> "_"
    in
    n :: trait_type_names t2
  | Ptyp_constr ({ txt = Longident.Lident n; _ }, []) -> [ n ]
  | _ -> [ "_" ]

let mkloc startpos endpos =
  { Location.loc_start = startpos; loc_end = endpos; loc_ghost = false }

let mkident loc txt =
  Ast_helper.Exp.ident ~loc (Location.mkloc (Longident.Lident txt) loc)

(* `Array.iter`: a real qualified reference into an existing OCaml module
   (stdlib, or one #use'd/generated by a trait's impl), built the same way
   the dispatch rewrite in bin/main.ml builds one. *)
let mkqident loc txt =
  let lid = match Longident.unflatten (String.split_on_char '.' txt) with
    | Some l -> l
    | None -> Longident.Lident txt
  in
  Ast_helper.Exp.ident ~loc (Location.mkloc lid loc)

let is_capitalized s = s <> "" && s.[0] >= 'A' && s.[0] <= 'Z'

let mkbool_pat loc b =
  Ast_helper.Pat.construct ~loc (Location.mkloc (Longident.Lident (if b then "true" else "false")) loc) None

(* `a[i]` calls the `[]` operator and `a[i] = v` the `[]=` one, once a trait
   declares them (`op [] of a -> b -> c`), so indexing works on any type
   with an impl (overloaded by container and index type, like `arithm`).
   Before that -- or without the stdlib -- it falls back to arrays. *)
let index_fn loc op fallback =
  match Hashtbl.find_opt operator_tbl op with
  | Some f -> mkident loc f
  | None -> mkqident loc fallback

(* Each call gets its own location (up to the end of its index): the
   overload picked for a call is recorded by location in bin/main.ml, so
   `m[i, j] = v`'s inner `[]` and outer `[]=` must not share one. *)
let mkget (loc : Location.t) arr (i : expression) =
  let loc = { loc with loc_end = i.pexp_loc.loc_end } in
  Ast_helper.Exp.apply ~loc (index_fn loc "[]" "Array.get") [ (Nolabel, arr); (Nolabel, i) ]

(* `m[i, j]` is `m[i][j]`, but `h[(i, j)]` is one tuple index (e.g. a
   key): told apart by whether the tuple starts right at the `[`'s
   content ([index_start]) or inside parentheses. *)
let split_indices (index : expression) index_start =
  match index.pexp_desc with
  | Pexp_tuple l when index.pexp_loc.loc_start.pos_cnum = index_start.Lexing.pos_cnum -> List.map snd l
  | _ -> [ index ]

(* `t[i] = v` -> `[]=` t i v; with several indices, like reading
   (`m[i, j]` is `m[i][j]`), all but the last one select the inner value:
   `m[i, j] = v` -> `[]=` (m[i]) j v. *)
let mkassign loc arr (index : expression) index_start v =
  let rec go arr = function
    | [ last ] -> Ast_helper.Exp.apply ~loc (index_fn loc "[]=" "Array.set") [ (Nolabel, arr); (Nolabel, last); (Nolabel, v) ]
    | i :: rest -> go (mkget loc arr i) rest
    | [] -> assert false
  in
  go arr (split_indices index index_start)

let mkbool loc b =
  Ast_helper.Exp.construct ~loc
    (Location.mkloc (Longident.Lident (if b then "true" else "false")) loc)
    None

let mkunit loc =
  Ast_helper.Exp.construct ~loc (Location.mkloc (Longident.Lident "()") loc) None

let known_types = [ "unit"; "int"; "float"; "string"; "bytes"; "bool"; "char" ]

(* How many type parameters a concrete (non-abstract) type needs, e.g.
   `array` needs exactly one (its element type). Everything else here is a
   leaf type with none. Mirrors `classify_texpr` in bin/main.ml, which
   recurses into exactly this many type arguments when classifying a self
   type at a dispatch call site. A type the program declares with
   parameters (`type a btree { ... }`) is registered in [user_type_arity]
   when parsed, so an impl further down sees it like `array`. *)
let user_type_arity : (string, int) Hashtbl.t = Hashtbl.create 16

let type_arity name =
  match name with
  | "array" | "list" | "option" -> 1
  | _ -> Option.value (Hashtbl.find_opt user_type_arity name) ~default:0

(* A name in a trait signature is always a TYPE NAME (concrete, e.g. `unit`,
   or abstract, e.g. `a`) -- never a type variable ['a]. A variable would let
   any impl's val be *more general* than required (fine) but never *more
   specific* (a concrete `string -> unit` can never match `'a -> unit`), so
   ascribing an impl's module against its trait's module type (see `impl`
   below) would always fail. Treating every name as a type reference, and
   auto-declaring the ones that aren't already known/concrete as abstract
   types on the trait itself, is what makes that ascription actually work. *)
let mk_type_component loc name =
  (* The lexer accepts `'` inside identifiers (for `x'`), so OCaml's own
     `'a` would otherwise reach the generated code as an invalid type name. *)
  if String.length name > 0 && name.[0] = '\'' then
    raise (Location.Error (Location.error ~loc
      (Printf.sprintf "Invalid type name `%s`: write type parameters without a quote, e.g. `%s`"
         name (String.sub name 1 (String.length name - 1)))));
  Ast_helper.Typ.constr ~loc (Location.mkloc (Longident.Lident name) loc) []

(* Every non-concrete name used across a trait's method signatures (e.g. `a`
   in `fn print of a -> unit`) is an abstract type the trait requires -- on
   top of whichever ones were declared explicitly via `type ...`. *)
let rec placeholder_names_in_type (ty : core_type) : string list =
  match ty.ptyp_desc with
  | Ptyp_arrow (_, t1, t2) -> placeholder_names_in_type t1 @ placeholder_names_in_type t2
  | Ptyp_constr ({ txt = Longident.Lident name; _ }, []) when not (List.mem name known_types) -> [ name ]
  (* `a t`: the constructor `t` itself is declared explicitly (`type t of
     1`); only its arguments may be placeholders. *)
  | Ptyp_constr (_, args) -> List.concat_map placeholder_names_in_type args
  | _ -> []

let make_value loc name (ty : core_type) =
  Ast_helper.Val.mk (Location.mkloc name loc) ty

let dedup_preserve_order lst =
  let seen = Hashtbl.create 16 in
  List.filter (fun x -> if Hashtbl.mem seen x then false else (Hashtbl.add seen x (); true)) lst

let mkfun loc pat body =
  Ast_helper.Exp.function_ ~loc
    [ { pparam_loc = loc; pparam_desc = Pparam_val (Nolabel, None, pat) } ]
    None
    (Pfunction_body body)

let mkbinop loc op e1 e2 =
  Ast_helper.Exp.apply ~loc (mkident loc op) [ (Nolabel, e1); (Nolabel, e2) ]

let mk_fn_expr loc params body =
  let param_pats =
    match params with
    | [] -> [ Ast_helper.Pat.construct (Location.mkloc (Longident.Lident "()") loc) None ]
    | _ -> List.map (fun p -> Ast_helper.Pat.var (Location.mkloc p loc)) params
  in
  List.fold_right (fun pat acc -> mkfun loc pat acc) param_pats body

(* [fn]/[fn]-nested have no `rec` keyword, so we infer it: a function is
   recursive iff it calls itself somewhere in its own body. We look for a
   direct application of an identifier with that exact name (e.g. [name arg]),
   walking the whole body (including nested lets/ifs/lambdas) via a generic
   Parsetree iterator (compiler-libs' [Ast_iterator]), rather than a
   hand-rolled AST walk. *)
let has_self_call name (body : expression) =
  let found = ref false in
  let expr (iter : Ast_iterator.iterator) (e : expression) =
    (match e.pexp_desc with
     | Pexp_apply ({ pexp_desc = Pexp_ident { txt = Longident.Lident fn; _ }; _ }, _)
       when fn = name -> found := true
     | _ -> ());
    Ast_iterator.default_iterator.expr iter e
  in
  let iterator = { Ast_iterator.default_iterator with expr } in
  iterator.expr iterator body;
  !found

(* Top-level [fn name(params) { body }]: becomes a structure-level binding,
   recursive iff [name] is called inside [body]. *)
let mkfn loc name params body =
  let rec_flag = if has_self_call name body then Recursive else Nonrecursive in
  Ast_helper.Str.value ~loc rec_flag
    [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) (mk_fn_expr loc params body) ]

(* Nested [fn name(params) { body } <rest>]: becomes a local function
   binding, i.e. sugar for [let (rec) name = fun params -> body in <rest>]. *)
let mklocalfn loc name params body rest =
  let rec_flag = if has_self_call name body then Recursive else Nonrecursive in
  Ast_helper.Exp.let_ ~loc rec_flag
    [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) (mk_fn_expr loc params body) ]
    rest

(* One method inside an `impl`. Zero params is a point-free alias -- e.g.
   `op + { scaml_add_int }` means [let (+) = scaml_add_int], reusing
   whatever arity/type [scaml_add_int] already has -- *not* a unit-taking
   function ([mk_fn_expr]'s usual meaning for zero params, needed elsewhere
   so that e.g. [fn main { .. }] stays callable as [main ()]). An impl's
   method must match the trait's declared arity exactly (checked by the
   module ascription in [item]'s IMPL rule), so wrapping it in an extra
   [fun () -> ..] would always fail that check. *)
(* Never auto-[rec]: unlike a plain top-level/local [fn], calling a name
   matching the current method from *inside* an impl body is ambiguous with
   calling another impl's (or a generic element's) same-named trait method
   -- a dispatch, not literal self-recursion -- and [has_self_call] can't
   tell the two apart from the name alone. bin/main.ml's dispatch rewrite
   resolves those calls instead; see [harvest_dispatch]'s [module_binding]
   handling. *)
let mkimplmethod loc name params body =
  match params with
  | [] ->
    Ast_helper.Str.value ~loc Nonrecursive
      [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) body ]
  | _ ->
    Ast_helper.Str.value ~loc Nonrecursive
      [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) (mk_fn_expr loc params body) ]

(* Annotates each curried parameter of an impl method that the trait's own
   signature declares as the self type (e.g. `a`) with that type name, e.g.
   `fn print a { ... }` becomes `let print (a : a) = ...` -- but *not*
   every parameter: `fold_left`'s `acc` and callback aren't self-typed
   (consulted via [method_sig_tbl], the method's own params-then-return
   chain from its trait declaration), and must stay untouched. Needed so
   that *probing* (bin/main.ml, which type-checks this body once up front
   using generic polymorphic stand-ins for every trait method, before it
   knows any real dispatch) can still see that a self-typed parameter
   really has the impl's own self type -- without this, nothing here ties
   an unannotated parameter back to it, since OCaml infers each binding's
   type from its own body alone, not from the signature it'll later be
   checked against. Harmless for a concrete impl (e.g. `showable of int`,
   where `a` already simply means `int`); essential for a generic one
   (`showable of array`, where `a` means `X.<elem> array` -- still
   abstract, abstract enough that probing otherwise can't tell a recursive
   call on an element from an unrelated type). Point-free methods (`op + {
   scaml_add_int }`) have no parameters to annotate and are left untouched. *)
let annotate_self_params self_name (methods : structure_item list) : structure_item list =
  let self_ty = Ast_helper.Typ.constr (Location.mknoloc (Longident.Lident self_name)) [] in
  let rec annotate_expr (chain : string list) (e : expression) : expression =
    match e.pexp_desc, chain with
    | Pexp_function ([ { pparam_desc = Pparam_val (lbl, def, pat); pparam_loc } ], c, Pfunction_body inner), param_ty :: rest ->
      let pat' =
        if param_ty = self_name then
          (match pat.ppat_desc with Ppat_var _ -> Ast_helper.Pat.constraint_ ~loc:pat.ppat_loc pat self_ty | _ -> pat)
        else pat
      in
      { e with pexp_desc = Pexp_function ([ { pparam_desc = Pparam_val (lbl, def, pat'); pparam_loc } ], c, Pfunction_body (annotate_expr rest inner)) }
    | _ -> e
  in
  List.map
    (fun (item : structure_item) ->
      match item.pstr_desc with
      | Pstr_value (rf, [ ({ pvb_pat = { ppat_desc = Ppat_var { txt = name; _ }; _ }; _ } as vb) ]) ->
        let chain = match Hashtbl.find_opt method_sig_tbl name with Some c -> c | None -> [] in
        { item with pstr_desc = Pstr_value (rf, [ { vb with pvb_expr = annotate_expr chain vb.pvb_expr } ]) }
      | _ -> item)
    methods

(* `impl <trait> of <ty>` for a trait whose self type is a constructor
   (`type t of 1`): the constructor is [ty] itself, and the methods stay
   polymorphic in everything else:

     module Mappable__array =
       (struct type 'x0 t = 'x0 array let map = Array.map end
        : mappable with type 'x0 t = 'x0 array) *)
let mkctorimpl loc mod_name trait_name ty ctor ctor_arity methods =
  if type_arity ty <> ctor_arity then
    raise (Location.Error (Location.error ~loc
      (Printf.sprintf "`%s` takes %d type parameter(s), but trait `%s`'s `%s` needs %d"
         ty (type_arity ty) trait_name ctor ctor_arity)));
  let params = ctor_params loc ctor_arity in
  let ctor_decl =
    Ast_helper.Type.mk ~loc ~params
      ~manifest:(Ast_helper.Typ.constr ~loc (Location.mkloc (Longident.Lident ty) loc) (List.map fst params))
      (Location.mkloc ctor loc)
  in
  let body =
    Ast_helper.Mod.constraint_ ~loc
      (Ast_helper.Mod.structure ~loc (Ast_helper.Str.type_ ~loc Recursive [ ctor_decl ] :: methods))
      (Ast_helper.Mty.with_ ~loc
         (Ast_helper.Mty.ident ~loc (Location.mkloc (Longident.Lident trait_name) loc))
         [ Pwith_type (Location.mkloc (Longident.Lident ctor) loc, ctor_decl) ])
  in
  Ast_helper.Str.module_ ~loc (Ast_helper.Mb.mk (Location.mkloc (Some mod_name) loc) body)

(* `impl <trait> of <ty1>, <ty2>, ...`: an overload chosen by the types of
   a method's first parameters (one per listed type), Rust `Mul<Rhs>`-style,
   instead of a single self type. Each method becomes a plain top-level
   function whose name records those types, with its parameters annotated
   accordingly (a parametric type's own arguments left open):

     impl mul of array, int { op * x k { ... } }
       ~>  let op___N_____ovl__array__int (x : _ array) (k : int) = ...

   bin/main.ml dispatches a call to the overload matching its arguments'
   types; a body that is generic (e.g. over the array's elements) is then
   specialized per use by its monomorphization. *)
let mkoverloadimpl loc trait_name (tys : string list) (methods : structure_item list) =
  if not (Hashtbl.mem trait_def trait_name) then
    raise (Location.Error (Location.error ~loc (Printf.sprintf "impl of unknown trait `%s`" trait_name)));
  let annot ty =
    Ast_helper.Typ.constr ~loc (Location.mkloc (Longident.Lident ty) loc)
      (List.init (type_arity ty) (fun _ -> Ast_helper.Typ.any ~loc ()))
  in
  let annots = List.map annot tys in
  let rec annotate annots (e : expression) =
    match annots, e.pexp_desc with
    | [], _ -> e
    | ty :: rest, Pexp_function ([ ({ pparam_desc = Pparam_val (lbl, def, pat); _ } as p) ], c, Pfunction_body body) ->
      let p' = { p with pparam_desc = Pparam_val (lbl, def, Ast_helper.Pat.constraint_ ~loc:pat.ppat_loc pat ty) } in
      { e with pexp_desc = Pexp_function ([ p' ], c, Pfunction_body (annotate rest body)) }
    | _ ->
      (* Point-free (`op * { scaml_tim_int }`): constrain the whole value. *)
      let fn_ty = List.fold_right (fun a acc -> Ast_helper.Typ.arrow ~loc Nolabel a acc) annots (Ast_helper.Typ.any ~loc ()) in
      Ast_helper.Exp.constraint_ ~loc e fn_ty
  in
  List.map
    (fun (item : structure_item) ->
      match item.pstr_desc with
      | Pstr_value (rf, [ ({ pvb_pat = { ppat_desc = Ppat_var { txt = name; loc = nloc }; _ } as pat; pvb_expr; _ } as vb) ]) ->
        let name' = name ^ "__ovl__" ^ String.concat "__" tys in
        { item with
          pstr_desc =
            Pstr_value
              (rf, [ { vb with pvb_pat = { pat with ppat_desc = Ppat_var (Location.mkloc name' nloc) }; pvb_expr = annotate annots pvb_expr } ]) }
      | _ -> item)
    methods

(* [#use "path"]: [path] is plain OCaml (not SCaml), so it's parsed with
   OCaml's own parser (Parse.implementation, the same entry point ocamlopt
   itself uses for a .ml file) rather than our lexer/parser, and its
   top-level bindings are spliced in directly -- no separate compilation
   unit, no .cmi. [Embedded.file] is checked first, so the stdlib's own
   `#use "stdlib/..."` resolves to the copy built into the compiler. *)
let load_used_file loc path : Parsetree.structure =
  let contents =
    match !Embedded.file path with
    | Some contents -> contents
    | None ->
      try In_channel.with_open_bin path In_channel.input_all
      with Sys_error msg -> raise (Location.Error (Location.error ~loc msg))
  in
  let lexbuf = Lexing.from_string contents in
  Lexing.set_filename lexbuf path;
  Parse.implementation lexbuf
%}

%token <int> INT
%token <char> CHAR
%token <string> IDENT FLOAT QIDENT
%token <string> OP_OR OP_AND OP_CMP OP_AT OP_CONS OP_ADD OP_MUL OP_POW
%token <string> STRING
%token LPAREN RPAREN LBRACE RBRACE COMMA SEMICOLON EQ LBRACK RBRACK
%token LET IF THEN ELSE FUN ARROW TRUE FALSE FN OP USE TRAIT IMPL TYPE OF
%token EOF DOT BAR MATCH INDEX_LBRACK LBRACKBAR BARRBRACK

(* Binary operators, lowest priority first, as in OCaml (see
   [Lexer.operator]): `1 + 2 * 3` is `1 + (2 * 3)`, `x :: l @ m` is
   `x :: (l @ m)`, `a + b |> f` is `(a + b) |> f`. *)
%right OP_OR
%right OP_AND
%left OP_CMP
%right OP_AT
%right OP_CONS
%left OP_ADD
%left OP_MUL
%right OP_POW
(* Prefix `-`: tighter than every binary operator (`-2 * 3` is `(-2) * 3`),
   looser than application (`-f x` is `-(f x)`), as in OCaml. *)
%nonassoc UMINUS
(* `match f x { ... }`: after the scrutinee, a `{` opens the arms rather than
   a record literal passed as one more argument (as in Rust; write
   `match f ({ x = 1 }) { ... }` for that). Only the scrutinee position is
   affected: nowhere else can an expression be followed by `{`. *)
%nonassoc LBRACE
%nonassoc below_arms

%start <Parsetree.structure> program

%%

program:
  | items = list(item); EOF { List.concat items }

(* An operator's name: a symbol (`+`, `|>`), or `[]` / `[]=` for what
   `a[i]` / `a[i] = v` call. *)
(* Inlined, so each use expands to one production per token and keeps that
   token's precedence (see the declarations above). *)
%inline binop:
  | c = OP_OR { c }
  | c = OP_AND { c }
  | c = OP_CMP { c }
  | c = OP_AT { c }
  | c = OP_CONS { c }
  | c = OP_ADD { c }
  | c = OP_MUL { c }
  | c = OP_POW { c }

op_name:
  | c = binop { c }
  | LBRACK; RBRACK { "[]" }
  | LBRACK; RBRACK; EQ { "[]=" }

fn_params:
  | LPAREN; params = separated_list(COMMA, IDENT); RPAREN { params }
  | params = list(IDENT) { params }

type_declaration:
  | t1 = type_atom; ARROW; rest = type_declaration
      { Ast_helper.Typ.arrow Nolabel t1 rest }
  | t = type_atom
      { t }

type_atom:
  | ty = IDENT
      { mk_type_component (mkloc $startpos $endpos) ty }
  | arg = type_atom; c = IDENT
      { let loc = mkloc $startpos $endpos in
        Ast_helper.Typ.constr ~loc (Location.mkloc (Longident.Lident c) loc) [ arg ] }
  | LPAREN; t = type_declaration; RPAREN
      { t }

type_declaration_trait_def:
  | ty = IDENT; rest = type_declaration_trait_def
      { let loc = mkloc $startpos $endpos in
        (Ast_helper.Type.mk (Location.mkloc ty loc)) :: rest }
  | ty = IDENT
      { let loc = mkloc $startpos $endpos in
        [ Ast_helper.Type.mk (Location.mkloc ty loc) ] }

impl_item:
  | FN; name = IDENT; params = fn_params; LBRACE; body = block; RBRACE
      { mkimplmethod (mkloc $startpos $endpos) name params body }
  | OP; name = op_name; params = fn_params; LBRACE; body = block; RBRACE
      { let loc = mkloc $startpos $endpos in
        let f_name =
          match Hashtbl.find_opt operator_tbl name with
          | Some f -> f
          | None ->
            raise (Location.Error
              (Location.error ~loc (Printf.sprintf "operator `%s` is not declared by any trait" name)))
        in
        mkimplmethod loc f_name params body }

(* Inside `impl <trait> of <ty> { ... }`: a method, or the concrete type for
   one of the trait's other abstract types (`type a = int`), which then
   stops being a parameter of the impl (e.g. `foldable`'s element type `a`
   is `int` for a `tree` of ints, while it stays free for `'a array`). *)
impl_entry:
  | m = impl_item { `Method m }
  | TYPE; n = IDENT; EQ; t = type_declaration
      { `Assoc (Location.mkloc n (mkloc $startpos(n) $endpos(n)), t) }

atom_body_trait_def:
  | OP; n = op_name; OF; t = type_declaration
      {
        let loc = mkloc $startpos $endpos in
        let f_name = "op___" ^ (string_of_int !operator_cnt) ^ "___" in
        incr operator_cnt;
        Hashtbl.add operator_tbl n f_name;
        Op_names.register n f_name;
        Hashtbl.replace method_sig_tbl f_name (trait_type_names t);
        Ast_helper.Sig.value ~loc (make_value loc f_name t)
      }
  | FN; n = IDENT; OF; t = type_declaration
      { let loc = mkloc $startpos $endpos in
        Hashtbl.replace method_sig_tbl n (trait_type_names t);
        Ast_helper.Sig.value ~loc (make_value loc n t) }
  | TYPE; t = type_declaration_trait_def
      { Ast_helper.Sig.type_ Recursive t }
  | TYPE; c = IDENT; OF; arity = INT
      { let loc = mkloc $startpos $endpos in
        Ast_helper.Sig.type_ ~loc Recursive
          [ Ast_helper.Type.mk ~loc ~params:(ctor_params loc arity) (Location.mkloc c loc) ] }

(* The inside of `type name { ... }`: either record fields separated by `;`
   (`name of string; age of int`) or constructors separated by `|`, with an
   optional leading `|` (`Leaf | Node of tree, int, tree`). A lone item is
   told apart by its case: `{ Empty }` is a constructor, `{ x of int }` a
   field. *)
body_type:
  | BAR; items = separated_nonempty_list(BAR, decl_item)
      { `Variant items }
  | first = decl_item; BAR; rest = separated_nonempty_list(BAR, decl_item)
      { `Variant (first :: rest) }
  | items = separated_nonempty_list(SEMICOLON, decl_item)
      { `Semi items }

decl_item:
  | name = IDENT; args = loption(preceded(OF, separated_nonempty_list(COMMA, type_declaration)))
      { (Location.mkloc name (mkloc $startpos $endpos), args) }

item:
  (* `type btree { ... }`, or with parameters before the name like OCaml's
     `'a btree` (without the quote): `type a btree { ... }`. *)
  | TYPE; ids = nonempty_list(IDENT); LBRACE; b = body_type; RBRACE
      {
        let loc = mkloc $startpos $endpos in
        let name, params = match List.rev ids with n :: ps -> n, List.rev ps | [] -> assert false in
        let c = { Location.txt = name; loc } in
        Hashtbl.replace user_type_arity name (List.length params);
        (* Inside the body, a parameter's name (`a` in `Node of a btree, a`)
           is that type variable, not a type of that name. *)
        let mapper =
          { Ast_mapper.default_mapper with
            typ = (fun m t ->
              match t.ptyp_desc with
              | Ptyp_constr ({ txt = Longident.Lident n; _ }, []) when List.mem n params ->
                Ast_helper.Typ.var ~loc:t.ptyp_loc n
              | _ -> Ast_mapper.default_mapper.typ m t) }
        in
        let b =
          match b with
          | `Variant items -> `Variant (List.map (fun (n, args) -> (n, List.map (mapper.typ mapper) args)) items)
          | `Semi items -> `Semi (List.map (fun (n, args) -> (n, List.map (mapper.typ mapper) args)) items)
        in
        let params = List.map (fun n -> (Ast_helper.Typ.var ~loc n, (Asttypes.NoVariance, Asttypes.NoInjectivity))) params in
        let is_ctor (n : string Location.loc) = n.txt <> "" && Char.uppercase_ascii n.txt.[0] = n.txt.[0] in
        let variant items =
          Ptype_variant
            (List.map
               (fun ((n : string Location.loc), args) ->
                 if not (is_ctor n) then
                   raise (Location.Error (Location.error ~loc:n.loc
                     (Printf.sprintf "constructor `%s` must start with an uppercase letter" n.txt)));
                 Ast_helper.Type.constructor ~loc:n.loc ~args:(Pcstr_tuple args) n)
               items)
        in
        let record items =
          Ptype_record
            (List.map
               (fun ((n : string Location.loc), args) ->
                 match args with
                 | [ t ] when not (is_ctor n) -> Ast_helper.Type.field ~loc:n.loc n t
                 | _ ->
                   raise (Location.Error (Location.error ~loc:n.loc
                     (if is_ctor n then Printf.sprintf "constructors are separated by `|`, not `;` (at `%s`)" n.txt
                      else Printf.sprintf "field `%s` needs exactly one type: `%s of <type>`" n.txt n.txt))))
               items)
        in
        let kind =
          match b with
          | `Variant items -> variant items
          | `Semi ([ (n, _) ] as items) when is_ctor n -> variant items
          | `Semi items -> record items
        in
        [ Ast_helper.Str.type_ Recursive [ Ast_helper.Type.mk ~loc ~params c ~kind ] ]
      }
  | FN; name = IDENT; params = fn_params;
    LBRACE; body = block; RBRACE
    { [ mkfn (mkloc $startpos $endpos) name params body ] }
  | OP; name = op_name; params = fn_params;
    LBRACE; body = block; RBRACE
    {
      let l = List.length params in
      let expected = if name = "[]=" then 3 else 2 in
      if l <> expected then raise (MyError (Printf.sprintf "Operator `%s` takes exactly %d arguments, but %d were given." name expected l));
      let f_name = "op___" ^ (string_of_int !operator_cnt) ^ "___" in
      incr operator_cnt;
      Hashtbl.add operator_tbl name f_name;
      Op_names.register name f_name;
      [ mkfn (mkloc $startpos $endpos) f_name params body ] }
  | USE; path = STRING
    { 
      load_used_file (mkloc $startpos $endpos) path 
    }
  | TRAIT; name = IDENT; LBRACE; sigs = list(atom_body_trait_def); RBRACE
    { 
      let loc = mkloc $startpos $endpos in
      let all_decls =
        List.concat_map
          (fun (si : signature_item) -> match si.psig_desc with Psig_type (_, decls) -> decls | _ -> [])
          sigs
      in
      let ctor_decls = List.filter (fun d -> d.ptype_params <> []) all_decls in
      let explicit_types = List.filter_map (fun d -> if d.ptype_params = [] then Some d.ptype_name.txt else None) all_decls in
      let placeholder_types =
        List.concat_map
          (fun (si : signature_item) ->
            match si.psig_desc with
            | Psig_value vd -> placeholder_names_in_type vd.pval_type
            | _ -> [])
          sigs
      in
      let ctor_names = List.map (fun d -> d.ptype_name.txt) ctor_decls in
      let abstract_types =
        dedup_preserve_order (explicit_types @ placeholder_types)
        |> List.filter (fun n -> not (List.mem n ctor_names))
      in
      (* The constructor, if any, comes last: bin/main.ml takes a trait's
         last declared type as its self type. *)
      let type_decls =
        List.map
          (fun n -> Ast_helper.Sig.type_ ~loc Recursive [ Ast_helper.Type.mk ~loc (Location.mkloc n loc) ])
          abstract_types
        @ List.map (fun d -> Ast_helper.Sig.type_ ~loc Recursive [ d ]) ctor_decls
      in
      (match ctor_decls with
       | [] -> ()
       | [ d ] -> Hashtbl.replace trait_ctor name (d.ptype_name.txt, List.length d.ptype_params)
       | _ -> raise (Location.Error (Location.error ~loc (Printf.sprintf "trait `%s` declares more than one type constructor" name))));
      let value_sigs = List.filter (fun (si : signature_item) -> match si.psig_desc with Psig_type _ -> false | _ -> true) sigs in
      (* With a constructor, `fn map of (a -> b) -> a t -> b t` means
         `val map : ('a -> 'b) -> 'a t -> 'b t`: one polymorphic impl per
         constructor, so a call site only has to pick the constructor. *)
      let abstract_types, type_decls, value_sigs =
        if ctor_decls = [] then abstract_types, type_decls, value_sigs
        else
          let typ (m : Ast_mapper.mapper) (t : core_type) =
            match t.ptyp_desc with
            | Ptyp_constr ({ txt = Longident.Lident n; _ }, []) when List.mem n abstract_types ->
              Ast_helper.Typ.var ~loc:t.ptyp_loc n
            | _ -> Ast_mapper.default_mapper.typ m t
          in
          let mapper = { Ast_mapper.default_mapper with typ } in
          ( [],
            List.map (fun d -> Ast_helper.Sig.type_ ~loc Recursive [ d ]) ctor_decls,
            List.map (mapper.signature_item mapper) value_sigs )
      in
      Hashtbl.replace trait_def name abstract_types;
      Hashtbl.replace trait_vals name value_sigs;
      [ Ast_helper.Str.modtype ~loc
          (Ast_helper.Mtd.mk (Location.mkloc name loc) ~typ:(Ast_helper.Mty.signature (type_decls @ value_sigs))) ] }
  | IMPL; trait_name = IDENT; OF; ty = IDENT; COMMA; tys = separated_nonempty_list(COMMA, IDENT);
    LBRACE; methods = list(impl_item); RBRACE
      { mkoverloadimpl (mkloc $startpos $endpos) trait_name (ty :: tys) methods }
  | IMPL; trait_name = IDENT; OF; ty = IDENT; LBRACE; entries = list(impl_entry); RBRACE
      { let loc = mkloc $startpos $endpos in
        let mod_name = String.capitalize_ascii (trait_name ^ "__" ^ ty) in
        let methods = List.filter_map (function `Method m -> Some m | `Assoc _ -> None) entries in
        let assoc = List.filter_map (function `Assoc (n, t) -> Some (n, t) | `Method _ -> None) entries in
        let assoc_error ((n : string Location.loc), _) msg = raise (Location.Error (Location.error ~loc:n.loc msg)) in
        match Hashtbl.find_opt trait_ctor trait_name with
        | Some (ctor, ctor_arity) ->
          (match assoc with
           | a :: _ -> assoc_error a (Printf.sprintf "trait `%s` takes no `type ... = ...` in its impls" trait_name)
           | [] -> ());
          [ mkctorimpl loc mod_name trait_name ty ctor ctor_arity methods ]
        | None ->
        let abstract_types =
          match Hashtbl.find_opt trait_def trait_name with
          | Some types -> types
          | None -> raise (Location.Error (Location.error ~loc (Printf.sprintf "impl of unknown trait `%s`" trait_name)))
        in
        let self_name, other_names =
          match List.rev abstract_types with
          | last :: rest -> Some last, List.rev rest
          | [] -> None, []
        in
        let tied_count = min (type_arity ty) (List.length other_names) in
        let other_count = List.length other_names in
        let free_names = List.filteri (fun i _ -> i < other_count - tied_count) other_names in
        let tied_names = List.filteri (fun i _ -> i >= other_count - tied_count) other_names in
        List.iter
          (fun ((n : string Location.loc), _ as a) ->
            if Some n.txt = self_name then
              assoc_error a (Printf.sprintf "`%s` is `%s` itself in this impl" n.txt ty)
            else if List.mem n.txt tied_names then
              assoc_error a (Printf.sprintf "`%s` is already given by `%s`'s own type parameter" n.txt ty)
            else if not (List.mem n.txt free_names) then
              assoc_error a (Printf.sprintf "trait `%s` has no abstract type `%s`" trait_name n.txt))
          assoc;
        let fixed n = List.find_map (fun ((m : string Location.loc), t) -> if m.txt = n then Some t else None) assoc in
        let free_names = List.filter (fun n -> fixed n = None) free_names in
        let pad_count = max 0 (type_arity ty - List.length tied_names) in
        let pad_names =
          List.init pad_count (fun i -> Printf.sprintf "__elem%d__" (List.length tied_names + i))
        in
        let applied_ty_args = tied_names @ pad_names in
        (* Only what the self type is built from is a functor parameter (the
           element type of an `array`...). The remaining "free" types (e.g.
           `foldable`'s `acc`) are type variables instead (see
           [module_type]): the methods stay polymorphic in them, so a call
           site never has to know them to pick this impl. *)
        let all_param_names = applied_ty_args in
        let functor_param = "X" in
        let other_ref n =
          if all_param_names = [] then Longident.Lident n else Option.get (Longident.unflatten [ functor_param; n ])
        in
        let applied_ty () =
          Ast_helper.Typ.constr ~loc (Location.mkloc (Longident.Lident ty) loc)
            (List.map (fun n -> Ast_helper.Typ.constr ~loc (Location.mkloc (other_ref n) loc) []) applied_ty_args)
        in
        let is_free n = List.mem n free_names in
        (* Every non-free type, with what it is in this impl. *)
        let manifest_of n =
          if Some n = self_name then applied_ty ()
          else match fixed n with
            | Some t -> t
            | None -> Ast_helper.Typ.constr ~loc (Location.mkloc (other_ref n) loc) []
        in
        let type_manifests =
          List.filter_map
            (fun n ->
              if is_free n then None
              else
                Some (Ast_helper.Str.type_ ~loc Recursive
                        [ Ast_helper.Type.mk ~loc ~manifest:(manifest_of n) (Location.mkloc n loc) ]))
            abstract_types
        in
        (* The trait's signature for this impl: its types as defined here,
           and its methods with every free type as a type variable
           (`val fold_left : ('acc -> a -> 'acc) -> 'acc -> b -> 'acc`). *)
        let module_type =
          let free_to_var =
            { Ast_mapper.default_mapper with
              typ = (fun m t ->
                match t.ptyp_desc with
                | Ptyp_constr ({ txt = Longident.Lident n; _ }, []) when is_free n -> Ast_helper.Typ.var ~loc:t.ptyp_loc n
                | _ -> Ast_mapper.default_mapper.typ m t) }
          in
          let type_sigs =
            List.filter_map
              (fun n ->
                if is_free n then None
                else
                  Some (Ast_helper.Sig.type_ ~loc Recursive
                          [ Ast_helper.Type.mk ~loc ~manifest:(manifest_of n) (Location.mkloc n loc) ]))
              abstract_types
          in
          let vals = Option.value (Hashtbl.find_opt trait_vals trait_name) ~default:[] in
          Ast_helper.Mty.signature ~loc (type_sigs @ List.map (free_to_var.signature_item free_to_var) vals)
        in
        let methods = match self_name with Some self -> annotate_self_params self methods | None -> methods in
        let body =
          Ast_helper.Mod.constraint_ ~loc
            (Ast_helper.Mod.structure ~loc (type_manifests @ methods))
            module_type
        in
        let mod_expr =
          if all_param_names = [] then body
          else
            let param_sig =
              Ast_helper.Mty.signature ~loc
                (List.map (fun n -> Ast_helper.Sig.type_ ~loc Recursive [ Ast_helper.Type.mk ~loc (Location.mkloc n loc) ]) all_param_names)
            in
            Ast_helper.Mod.functor_ ~loc (Named (Location.mkloc (Some functor_param) loc, param_sig)) body
        in
        [ Ast_helper.Str.module_ ~loc (Ast_helper.Mb.mk (Location.mkloc (Some mod_name) loc) mod_expr) ] }

block:
  | FN; name = IDENT; params = fn_params;
    LBRACE; fbody = block; RBRACE; rest = block
    { 
      mklocalfn (mkloc $startpos $endpos) name params fbody rest 
    }
  | OP; name = op_name; params = fn_params;
    LBRACE; fbody = block; RBRACE; rest = block
    {
      let l = List.length params in
      let expected = if name = "[]=" then 3 else 2 in
      if l <> expected then raise (MyError (Printf.sprintf "Operator `%s` takes exactly %d arguments, but %d were given." name expected l));
      let f_name = "op___" ^ (string_of_int !operator_cnt) ^ "___" in
      incr operator_cnt;
      Hashtbl.add operator_tbl name f_name;
      Op_names.register name f_name;
      mklocalfn (mkloc $startpos $endpos) f_name params fbody rest 
    }
  (* `let x = e;`, or any pattern: `let (a, b) = e;`, `let a, b = e;`,
     `let { name; age } = p;`... *)
  | LET; p = let_pattern; EQ; e1 = expr; SEMICOLON; e2 = block
    { 
      let loc = mkloc $startpos $endpos in
      Ast_helper.Exp.let_ ~loc Nonrecursive [ Ast_helper.Vb.mk p e1 ] e2
    }
  | e1 = expr; SEMICOLON; b = block
    { 
      let loc = mkloc $startpos $endpos in
      Ast_helper.Exp.sequence ~loc e1 b
    }
  | e = expr; SEMICOLON | e = expr 
      { e }
  (* `t[i] = v;`, sugar for `Array.set t i v` (`m[i][j] = v` sets in `m[i]`). *)
  | a = assignment; SEMICOLON; b = block
    { Ast_helper.Exp.sequence ~loc:(mkloc $startpos $endpos) a b }
  | a = assignment; SEMICOLON | a = assignment
      { a }

assignment:
  | a = indexable; INDEX_LBRACK; index = expr; RBRACK; EQ; v = expr
    { mkassign (mkloc $startpos $endpos) a index $startpos(index) v }

body:
  | LBRACE; b = block; RBRACE
      { b }
  | e = expr
      { e }
  (* `^j -> t[j] = false`, `if c then t[i] = 0 else ()`: no braces needed. *)
  | a = assignment
      { a }

expr:
  | IF; c = expr; THEN; t = body; ELSE; e = body
    { Ast_helper.Exp.ifthenelse ~loc:(mkloc $startpos $endpos) c t (Some e) }
  | FUN; params = nonempty_list(IDENT); ARROW; e = body
    { mk_fn_expr (mkloc $startpos $endpos) params e }
  | MATCH; e = expr; LBRACE; option(BAR); cases = separated_nonempty_list(BAR, match_case); RBRACE
    { Ast_helper.Exp.match_ ~loc:(mkloc $startpos $endpos) e cases }
  | e = tuple { e }

(* A tuple needs no parentheses here, as in match arms. *)
let_pattern:
  | p = pattern { p }
  | first = pattern; COMMA; rest = separated_nonempty_list(COMMA, pattern)
    { Ast_helper.Pat.tuple ~loc:(mkloc $startpos $endpos) (List.map (fun p -> (None, p)) (first :: rest)) Closed }

match_case:
  | p = pattern; ARROW; e = body
    { Ast_helper.Exp.case p e }
  (* `match a, b { x, y -> ... }`: a tuple needs no parentheses here, just
     like the scrutinee itself. *)
  | first = pattern; COMMA; rest = separated_nonempty_list(COMMA, pattern); ARROW; e = body
    { let p = Ast_helper.Pat.tuple ~loc:(mkloc $startpos(first) $endpos(rest)) (List.map (fun p -> (None, p)) (first :: rest)) Closed in
      Ast_helper.Exp.case p e }

(* `x :: rest`, right-associative (`a :: b :: rest`). The only operator
   allowed in a pattern, besides `-` before a number (see [simple_pattern]). *)
pattern:
  | hd = app_pattern; c = OP_CONS; tl = pattern
    { let loc = mkloc $startpos $endpos in
      Ast_helper.Pat.construct ~loc (Location.mkloc (Longident.Lident "::") (mkloc $startpos(c) $endpos(c)))
        (Some ([], Ast_helper.Pat.tuple ~loc (List.map (fun p -> (None, p)) [ hd; tl ]) Closed)) }
  | p = app_pattern { p }

(* `Node (l, v, r)`, `Just x`: a constructor applied to one simple pattern
   (a tuple for several arguments, as in expressions). *)
app_pattern:
  | c = IDENT; arg = simple_pattern
    { let loc = mkloc $startpos $endpos in
      if not (is_capitalized c) then
        raise (Location.Error (Location.error ~loc
          (Printf.sprintf "only a constructor can take an argument in a pattern, not `%s`" c)));
      Ast_helper.Pat.construct ~loc (Location.mkloc (Longident.Lident c) (mkloc $startpos(c) $endpos(c))) (Some ([], arg)) }
  | p = simple_pattern { p }

simple_pattern:
  | x = IDENT
    { let loc = mkloc $startpos $endpos in
      if x = "_" then Ast_helper.Pat.any ~loc ()
      else if is_capitalized x then Ast_helper.Pat.construct ~loc (Location.mkloc (Longident.Lident x) loc) None
      else Ast_helper.Pat.var ~loc (Location.mkloc x loc) }
  | n = INT { Ast_helper.Pat.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.int n) }
  | c = OP_ADD; n = INT
      { let loc = mkloc $startpos $endpos in
        if c <> "-" then
          raise (Location.Error (Location.error ~loc:(mkloc $startpos(c) $endpos(c))
            (Printf.sprintf "`%s` can't be used in a pattern (only `-` before a number)" c)));
        Ast_helper.Pat.constant ~loc (Ast_helper.Const.int (- n)) }
  | c = OP_ADD; f = FLOAT
      { let loc = mkloc $startpos $endpos in
        if c <> "-" then
          raise (Location.Error (Location.error ~loc:(mkloc $startpos(c) $endpos(c))
            (Printf.sprintf "`%s` can't be used in a pattern (only `-` before a number)" c)));
        Ast_helper.Pat.constant ~loc (Ast_helper.Const.float ("-" ^ f)) }
  | s = STRING { Ast_helper.Pat.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.string s) }
  | c = CHAR { Ast_helper.Pat.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.char c) }
  | TRUE { mkbool_pat (mkloc $startpos $endpos) true }
  | FALSE { mkbool_pat (mkloc $startpos $endpos) false }
  | LPAREN; RPAREN
    { let loc = mkloc $startpos $endpos in
      Ast_helper.Pat.construct ~loc (Location.mkloc (Longident.Lident "()") loc) None }
  | LPAREN; p = pattern; RPAREN { p }
  | LPAREN; first = pattern; COMMA; rest = separated_nonempty_list(COMMA, pattern); RPAREN
    { Ast_helper.Pat.tuple ~loc:(mkloc $startpos $endpos) (List.map (fun p -> (None, p)) (first :: rest)) Closed }
  (* `[]`, `[x]`, `[a; b]`: a list of exactly that length, built like the
     list literal (`a :: (b :: [])`). *)
  | LBRACK; ps = separated_list(SEMICOLON, pattern); RBRACK
    { let loc = mkloc $startpos $endpos in
      let ctor name arg = Ast_helper.Pat.construct ~loc (Location.mkloc (Longident.Lident name) loc) arg in
      List.fold_right
        (fun p acc -> ctor "::" (Some ([], Ast_helper.Pat.tuple ~loc [ (None, p); (None, acc) ] Closed)))
        ps (ctor "[]" None) }
  (* `{ name = n; age }`: a field alone binds a variable of the same name. *)
  | LBRACE; fields = separated_nonempty_list(SEMICOLON, field_pattern); RBRACE
    { Ast_helper.Pat.record ~loc:(mkloc $startpos $endpos) fields Open }

field_pattern:
  | f = IDENT; p = option(preceded(EQ, pattern))
    { let floc = mkloc $startpos(f) $endpos(f) in
      let p = match p with Some p -> p | None -> Ast_helper.Pat.var ~loc:floc (Location.mkloc f floc) in
      (Location.mkloc (Longident.Lident f) floc, p) }

expr_bin:
  | e1 = expr_bin; c = binop; e2 = expr_bin
      {
        let f_name = match Hashtbl.find_opt operator_tbl c with Some f -> f | None -> c in
        let f_ident = mkident (mkloc $startpos(c) $endpos(c)) f_name in
        Ast_helper.Exp.apply ~loc:(mkloc $startpos $endpos) f_ident [(Nolabel, e1); (Nolabel, e2)] 
      }
  (* `-1`, `-2.5`: a negative literal. `-e` on anything else is a call to
     the stdlib's `neg` (trait `negatable`), so it works on every type that
     implements it, like the binary operators do. Only after an operator or
     where an expression starts: `f -1` stays a subtraction, write `f (-1)`. *)
  | c = OP_ADD; e = expr_bin %prec UMINUS
      { let loc = mkloc $startpos $endpos in
        if c <> "-" then
          raise (Location.Error (Location.error ~loc:(mkloc $startpos(c) $endpos(c))
            (Printf.sprintf "`%s` can't be used as a prefix operator (only `-`)" c)));
        match e.pexp_desc with
        | Pexp_constant { pconst_desc = Pconst_integer (n, None); _ } when n.[0] <> '-' ->
          Ast_helper.Exp.constant ~loc (Ast_helper.Const.integer ("-" ^ n))
        | Pexp_constant { pconst_desc = Pconst_float (f, None); _ } when f.[0] <> '-' ->
          Ast_helper.Exp.constant ~loc (Ast_helper.Const.float ("-" ^ f))
        | _ -> Ast_helper.Exp.apply ~loc (mkident (mkloc $startpos(c) $endpos(c)) "neg") [ (Nolabel, e) ] }
  | e = app %prec below_arms { e }

tuple:
  | first = expr_bin; COMMA; rest = separated_nonempty_list(COMMA, expr_bin)
      { 
        let all = first :: rest in
        Ast_helper.Exp.tuple ~loc:(mkloc $startpos $endpos) (List.map (fun e -> (None, e)) all)
      }
  | e = expr_bin { e }
  
indexable:
  | a = indexable; INDEX_LBRACK; index = expr; RBRACK
      { let loc = mkloc $startpos $endpos in
        List.fold_left (mkget loc) a (split_indices index $startpos(index)) }
  | e = indexable; DOT; f = IDENT
    {
      Ast_helper.Exp.field ~loc:(mkloc $startpos $endpos) e
          (Location.mkloc (Longident.Lident f) (mkloc $startpos(f) $endpos(f)))
    }
  | a = atom { a }

app:
  | e1 = app; e2 = indexable
    { let loc = mkloc $startpos $endpos in
      match e1.pexp_desc with
      (* `Some x`, `Node (l, v, r)`: a constructor takes its argument
         directly (a tuple for several), it isn't a function application. *)
      | Pexp_construct (c, None) -> Ast_helper.Exp.construct ~loc c (Some e2)
      | _ -> Ast_helper.Exp.apply ~loc e1 [ (Nolabel, e2) ] }
  | e = indexable { e }

atom:
  | n = INT { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.int n) }
  | s = STRING { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.string s) }
  | f = FLOAT { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.float f) }
  | c = CHAR { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.char c) }
  | TRUE { mkbool (mkloc $startpos $endpos) true }
  | FALSE { mkbool (mkloc $startpos $endpos) false }
  | x = IDENT
      { let loc = mkloc $startpos $endpos in
        if Char.uppercase_ascii x.[0] = x.[0] && x.[0] <> '_' && x.[0] <> '\''
        then Ast_helper.Exp.construct ~loc (Location.mkloc (Longident.Lident x) loc) None
        else mkident loc x }
  | q = QIDENT { mkqident (mkloc $startpos $endpos) q }
  | LPAREN; RPAREN { mkunit (mkloc $startpos $endpos) }
  | LPAREN; c = binop; RPAREN
      { 
        let loc = mkloc $startpos $endpos in
        let f_name = match Hashtbl.find_opt operator_tbl c with Some f -> f | None -> c in
        mkident loc f_name 
      }
  | LPAREN; e = expr; RPAREN 
      { e }
  | LBRACE; fs = separated_nonempty_list(SEMICOLON, record_field); RBRACE
      { 
        Ast_helper.Exp.record ~loc:(mkloc $startpos $endpos) fs None
      }

  (* `[| 1; 2; 3 |]`, or `[||]` for an empty array. *)
  | LBRACKBAR; fs = separated_list(SEMICOLON, expr); BARRBRACK
      { Ast_helper.Exp.array ~loc:(mkloc $startpos $endpos) fs }

  (* `[1; 2; 3]`, or `[]`: built like OCaml does, as `1 :: (2 :: (3 :: []))`. *)
  | LBRACK; fs = separated_list(SEMICOLON, expr); RBRACK
      { let loc = mkloc $startpos $endpos in
        let ctor name arg = Ast_helper.Exp.construct ~loc (Location.mkloc (Longident.Lident name) loc) arg in
        List.fold_right
          (fun e acc -> ctor "::" (Some (Ast_helper.Exp.tuple ~loc [ (None, e); (None, acc) ])))
          fs (ctor "[]" None) }

record_field:
  | f = IDENT; EQ; e = expr
      {
        (Location.mkloc (Longident.Lident f) (mkloc $startpos(f) $endpos(f)), e)
      }
