%{
(* Builds nodes of OCaml's own [Parsetree], not a custom AST: this parser
   produces real [Parsetree.structure] / [Parsetree.expression] values, which
   is what lets the rest of the pipeline hand them straight to the OCaml
   type-checker (compiler-libs' [Typemod]/[Typecore]) and pretty-printer
   ([Pprintast]). *)
open Parsetree
open Asttypes

let operator_cnt = ref 0
let operator_tbl = Hashtbl.create 97

let trait_def = Hashtbl.create 97

(* Per trait method name (e.g. "print", "fold_left", or an operator's
   generated "op___N___"): its full params-then-return type-name chain,
   e.g. ["a"; "a"; "bool"] for `a -> a -> bool` (same convention as
   bin/main.ml's [collect_trait_methods]: "_" marks a non-bare-name
   position, such as a function type like `(a -> unit)`). Filled in by
   [atom_body_trait_def] when a trait declares the method; consulted by
   [annotate_self_params] to know *which* of an impl's own parameters
   actually are the self type (and so need annotating) -- not every
   parameter is, e.g. `foldable`'s `fold_left`'s `acc` and callback aren't. *)
let method_sig_tbl : (string, string list) Hashtbl.t = Hashtbl.create 97

let rec trait_type_names (ty : core_type) : string list =
  match ty.ptyp_desc with
  | Ptyp_arrow (_, t1, t2) ->
    let n =
      match t1.ptyp_desc with
      | Ptyp_constr ({ txt = Longident.Lident n; _ }, []) -> n
      | _ -> "_"
    in
    n :: trait_type_names t2
  | Ptyp_constr ({ txt = Longident.Lident n; _ }, []) -> [ n ]
  | _ -> [ "_" ]

let mkloc startpos endpos =
  { Location.loc_start = startpos; loc_end = endpos; loc_ghost = false }

let mkident loc txt =
  Ast_helper.Exp.ident ~loc (Location.mkloc (Longident.Lident txt) loc)

(* `Array.iter`: a real qualified reference into an existing OCaml module
   (stdlib, or one #use'd/generated by a trait's impl), built the same way
   the dispatch rewrite in bin/main.ml builds one. *)
let mkqident loc txt =
  let lid = match Longident.unflatten (String.split_on_char '.' txt) with
    | Some l -> l
    | None -> Longident.Lident txt
  in
  Ast_helper.Exp.ident ~loc (Location.mkloc lid loc)

let mkbool loc b =
  Ast_helper.Exp.construct ~loc
    (Location.mkloc (Longident.Lident (if b then "true" else "false")) loc)
    None

let mkunit loc =
  Ast_helper.Exp.construct ~loc (Location.mkloc (Longident.Lident "()") loc) None

let known_types = [ "unit"; "int"; "float"; "string"; "bool"; "char" ]

(* How many type parameters a concrete (non-abstract) type needs, e.g.
   `array` needs exactly one (its element type). Everything else here is a
   leaf type with none. Mirrors `classify_texpr` in bin/main.ml, which
   recurses into exactly this many type arguments when classifying a self
   type at a dispatch call site. *)
let type_arity name = match name with "array" -> 1 | _ -> 0

(* A name in a trait signature is always a TYPE NAME (concrete, e.g. `unit`,
   or abstract, e.g. `a`) -- never a type variable ['a]. A variable would let
   any impl's val be *more general* than required (fine) but never *more
   specific* (a concrete `string -> unit` can never match `'a -> unit`), so
   ascribing an impl's module against its trait's module type (see `impl`
   below) would always fail. Treating every name as a type reference, and
   auto-declaring the ones that aren't already known/concrete as abstract
   types on the trait itself, is what makes that ascription actually work. *)
let mk_type_component loc name =
  Ast_helper.Typ.constr ~loc (Location.mkloc (Longident.Lident name) loc) []

(* Every non-concrete name used across a trait's method signatures (e.g. `a`
   in `fn print of a -> unit`) is an abstract type the trait requires -- on
   top of whichever ones were declared explicitly via `type ...`. *)
let rec placeholder_names_in_type (ty : core_type) : string list =
  match ty.ptyp_desc with
  | Ptyp_arrow (_, t1, t2) -> placeholder_names_in_type t1 @ placeholder_names_in_type t2
  | Ptyp_constr ({ txt = Longident.Lident name; _ }, []) when not (List.mem name known_types) -> [ name ]
  | _ -> []

let make_value loc name (ty : core_type) =
  Ast_helper.Val.mk (Location.mkloc name loc) ty

let dedup_preserve_order lst =
  let seen = Hashtbl.create 16 in
  List.filter (fun x -> if Hashtbl.mem seen x then false else (Hashtbl.add seen x (); true)) lst

let mkfun loc pat body =
  Ast_helper.Exp.function_ ~loc
    [ { pparam_loc = loc; pparam_desc = Pparam_val (Nolabel, None, pat) } ]
    None
    (Pfunction_body body)

let mkbinop loc op e1 e2 =
  Ast_helper.Exp.apply ~loc (mkident loc op) [ (Nolabel, e1); (Nolabel, e2) ]

let mk_fn_expr loc params body =
  let param_pats =
    match params with
    | [] -> [ Ast_helper.Pat.construct (Location.mkloc (Longident.Lident "()") loc) None ]
    | _ -> List.map (fun p -> Ast_helper.Pat.var (Location.mkloc p loc)) params
  in
  List.fold_right (fun pat acc -> mkfun loc pat acc) param_pats body

(* [fn]/[fn]-nested have no `rec` keyword, so we infer it: a function is
   recursive iff it calls itself somewhere in its own body. We look for a
   direct application of an identifier with that exact name (e.g. [name arg]),
   walking the whole body (including nested lets/ifs/lambdas) via a generic
   Parsetree iterator (compiler-libs' [Ast_iterator]), rather than a
   hand-rolled AST walk. *)
let has_self_call name (body : expression) =
  let found = ref false in
  let expr (iter : Ast_iterator.iterator) (e : expression) =
    (match e.pexp_desc with
     | Pexp_apply ({ pexp_desc = Pexp_ident { txt = Longident.Lident fn; _ }; _ }, _)
       when fn = name -> found := true
     | _ -> ());
    Ast_iterator.default_iterator.expr iter e
  in
  let iterator = { Ast_iterator.default_iterator with expr } in
  iterator.expr iterator body;
  !found

(* Top-level [fn name(params) { body }]: becomes a structure-level binding,
   recursive iff [name] is called inside [body]. *)
let mkfn loc name params body =
  let rec_flag = if has_self_call name body then Recursive else Nonrecursive in
  Ast_helper.Str.value ~loc rec_flag
    [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) (mk_fn_expr loc params body) ]

(* Nested [fn name(params) { body } <rest>]: becomes a local function
   binding, i.e. sugar for [let (rec) name = fun params -> body in <rest>]. *)
let mklocalfn loc name params body rest =
  let rec_flag = if has_self_call name body then Recursive else Nonrecursive in
  Ast_helper.Exp.let_ ~loc rec_flag
    [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) (mk_fn_expr loc params body) ]
    rest

(* One method inside an `impl`. Zero params is a point-free alias -- e.g.
   `op + { scaml_add_int }` means [let (+) = scaml_add_int], reusing
   whatever arity/type [scaml_add_int] already has -- *not* a unit-taking
   function ([mk_fn_expr]'s usual meaning for zero params, needed elsewhere
   so that e.g. [fn main { .. }] stays callable as [main ()]). An impl's
   method must match the trait's declared arity exactly (checked by the
   module ascription in [item]'s IMPL rule), so wrapping it in an extra
   [fun () -> ..] would always fail that check. *)
(* Never auto-[rec]: unlike a plain top-level/local [fn], calling a name
   matching the current method from *inside* an impl body is ambiguous with
   calling another impl's (or a generic element's) same-named trait method
   -- a dispatch, not literal self-recursion -- and [has_self_call] can't
   tell the two apart from the name alone. bin/main.ml's dispatch rewrite
   resolves those calls instead; see [harvest_dispatch]'s [module_binding]
   handling. *)
let mkimplmethod loc name params body =
  match params with
  | [] ->
    Ast_helper.Str.value ~loc Nonrecursive
      [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) body ]
  | _ ->
    Ast_helper.Str.value ~loc Nonrecursive
      [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc name loc)) (mk_fn_expr loc params body) ]

(* Annotates each curried parameter of an impl method that the trait's own
   signature declares as the self type (e.g. `a`) with that type name, e.g.
   `fn print a { ... }` becomes `let print (a : a) = ...` -- but *not*
   every parameter: `fold_left`'s `acc` and callback aren't self-typed
   (consulted via [method_sig_tbl], the method's own params-then-return
   chain from its trait declaration), and must stay untouched. Needed so
   that *probing* (bin/main.ml, which type-checks this body once up front
   using generic polymorphic stand-ins for every trait method, before it
   knows any real dispatch) can still see that a self-typed parameter
   really has the impl's own self type -- without this, nothing here ties
   an unannotated parameter back to it, since OCaml infers each binding's
   type from its own body alone, not from the signature it'll later be
   checked against. Harmless for a concrete impl (e.g. `showable of int`,
   where `a` already simply means `int`); essential for a generic one
   (`showable of array`, where `a` means `X.<elem> array` -- still
   abstract, abstract enough that probing otherwise can't tell a recursive
   call on an element from an unrelated type). Point-free methods (`op + {
   scaml_add_int }`) have no parameters to annotate and are left untouched. *)
let annotate_self_params self_name (methods : structure_item list) : structure_item list =
  let self_ty = Ast_helper.Typ.constr (Location.mknoloc (Longident.Lident self_name)) [] in
  let rec annotate_expr (chain : string list) (e : expression) : expression =
    match e.pexp_desc, chain with
    | Pexp_function ([ { pparam_desc = Pparam_val (lbl, def, pat); pparam_loc } ], c, Pfunction_body inner), param_ty :: rest ->
      let pat' =
        if param_ty = self_name then
          (match pat.ppat_desc with Ppat_var _ -> Ast_helper.Pat.constraint_ ~loc:pat.ppat_loc pat self_ty | _ -> pat)
        else pat
      in
      { e with pexp_desc = Pexp_function ([ { pparam_desc = Pparam_val (lbl, def, pat'); pparam_loc } ], c, Pfunction_body (annotate_expr rest inner)) }
    | _ -> e
  in
  List.map
    (fun (item : structure_item) ->
      match item.pstr_desc with
      | Pstr_value (rf, [ ({ pvb_pat = { ppat_desc = Ppat_var { txt = name; _ }; _ }; _ } as vb) ]) ->
        let chain = match Hashtbl.find_opt method_sig_tbl name with Some c -> c | None -> [] in
        { item with pstr_desc = Pstr_value (rf, [ { vb with pvb_expr = annotate_expr chain vb.pvb_expr } ]) }
      | _ -> item)
    methods

(* [#use "path"]: [path] is plain OCaml (not SCaml), so it's parsed with
   OCaml's own parser (Parse.implementation, the same entry point ocamlopt
   itself uses for a .ml file) rather than our lexer/parser, and its
   top-level bindings are spliced in directly -- no separate compilation
   unit, no .cmi. *)
let load_used_file loc path : Parsetree.structure =
  let ic =
    try open_in path
    with Sys_error msg -> raise (Location.Error (Location.error ~loc msg))
  in
  let lexbuf = Lexing.from_channel ic in
  Lexing.set_filename lexbuf path;
  match Parse.implementation lexbuf with
  | structure -> close_in ic; structure
  | exception exn -> close_in ic; raise exn
%}

%token <int> INT
%token <char> CHAR
%token <string> IDENT CUSTOM FLOAT QIDENT
%token <string> STRING
%token LPAREN RPAREN LBRACE RBRACE COMMA SEMICOLON EQ LBRACK RBRACK
%token LET IF THEN ELSE FUN ARROW TRUE FALSE FN OP USE TRAIT IMPL TYPE OF
%token EOF

%left CUSTOM

%start <Parsetree.structure> program

%%

program:
  | items = list(item); EOF { List.concat items }

fn_params:
  | LPAREN; params = separated_list(COMMA, IDENT); RPAREN { params }
  | params = list(IDENT) { params }

type_declaration:
  | t1 = type_atom; ARROW; rest = type_declaration
      { Ast_helper.Typ.arrow Nolabel t1 rest }
  | t = type_atom
      { t }

type_atom:
  | ty = IDENT
      { mk_type_component (mkloc $startpos $endpos) ty }
  | LPAREN; t = type_declaration; RPAREN
      { t }

type_declaration_trait_def:
  | ty = IDENT; rest = type_declaration_trait_def
      { let loc = mkloc $startpos $endpos in
        (Ast_helper.Type.mk (Location.mkloc ty loc)) :: rest }
  | ty = IDENT
      { let loc = mkloc $startpos $endpos in
        [ Ast_helper.Type.mk (Location.mkloc ty loc) ] }

impl_item:
  | FN; name = IDENT; params = fn_params; LBRACE; body = block; RBRACE
      { mkimplmethod (mkloc $startpos $endpos) name params body }
  | OP; name = CUSTOM; params = fn_params; LBRACE; body = block; RBRACE
      { let loc = mkloc $startpos $endpos in
        let f_name =
          match Hashtbl.find_opt operator_tbl name with
          | Some f -> f
          | None ->
            raise (Location.Error
              (Location.error ~loc (Printf.sprintf "operator `%s` is not declared by any trait" name)))
        in
        mkimplmethod loc f_name params body }

atom_body_trait_def:
  | OP; n = CUSTOM; OF; t = type_declaration
      {
        let loc = mkloc $startpos $endpos in
        let f_name = "op___" ^ (string_of_int !operator_cnt) ^ "___" in
        incr operator_cnt;
        Hashtbl.add operator_tbl n f_name;
        Hashtbl.replace method_sig_tbl f_name (trait_type_names t);
        Ast_helper.Sig.value ~loc (make_value loc f_name t)
      }
  | FN; n = IDENT; OF; t = type_declaration
      { let loc = mkloc $startpos $endpos in
        Hashtbl.replace method_sig_tbl n (trait_type_names t);
        Ast_helper.Sig.value ~loc (make_value loc n t) }
  | TYPE; t = type_declaration_trait_def
      { Ast_helper.Sig.type_ Recursive t }

item:
  | FN; name = IDENT; params = fn_params;
    LBRACE; body = block; RBRACE
    { [ mkfn (mkloc $startpos $endpos) name params body ] }
  | OP; name = CUSTOM; params = fn_params;
    LBRACE; body = block; RBRACE
    {
      let f_name = "op___" ^ (string_of_int !operator_cnt) ^ "___" in
      incr operator_cnt;
      Hashtbl.add operator_tbl name f_name;
      [ mkfn (mkloc $startpos $endpos) f_name params body ] }
  | USE; path = STRING
    { load_used_file (mkloc $startpos $endpos) path }
  | TRAIT; name = IDENT; LBRACE; sigs = list(atom_body_trait_def); RBRACE
    { 
      let loc = mkloc $startpos $endpos in
      let explicit_types =
        List.concat_map
          (fun (si : signature_item) ->
            match si.psig_desc with
            | Psig_type (_, decls) -> List.map (fun d -> d.ptype_name.txt) decls
            | _ -> [])
          sigs
      in
      let placeholder_types =
        List.concat_map
          (fun (si : signature_item) ->
            match si.psig_desc with
            | Psig_value vd -> placeholder_names_in_type vd.pval_type
            | _ -> [])
          sigs
      in
      let abstract_types = dedup_preserve_order (explicit_types @ placeholder_types) in
      let type_decls =
        List.map
          (fun n -> Ast_helper.Sig.type_ ~loc Recursive [ Ast_helper.Type.mk ~loc (Location.mkloc n loc) ])
          abstract_types
      in
      let value_sigs = List.filter (fun (si : signature_item) -> match si.psig_desc with Psig_type _ -> false | _ -> true) sigs in
      Hashtbl.replace trait_def name abstract_types;
      [ Ast_helper.Str.modtype ~loc
          (Ast_helper.Mtd.mk (Location.mkloc name loc) ~typ:(Ast_helper.Mty.signature (type_decls @ value_sigs))) ] }
  | IMPL; trait_name = IDENT; OF; ty = IDENT; LBRACE; methods = list(impl_item); RBRACE
      { let loc = mkloc $startpos $endpos in
        let mod_name = String.capitalize_ascii (trait_name ^ "__" ^ ty) in
        let abstract_types =
          match Hashtbl.find_opt trait_def trait_name with
          | Some types -> types
          | None -> raise (Location.Error (Location.error ~loc (Printf.sprintf "impl of unknown trait `%s`" trait_name)))
        in
        let self_name, other_names =
          match List.rev abstract_types with
          | last :: rest -> Some last, List.rev rest
          | [] -> None, []
        in
        (* Not every "other" abstract type is one of [ty]'s own type
           constructor arguments -- e.g. `foldable { type acc a b }`'s `acc`
           has nothing to do with `array`'s element type (only `a` does);
           it's a genuinely free/polymorphic type, resolved at each *call
           site* from whatever argument actually plays that role there
           (e.g. the `0` in `fold_left (+) 0 arr`), not from [ty]'s own
           structure. Convention: the *last* [type_arity ty] "other" names,
           in declared order, are "tied" to [ty]'s own constructor arguments
           (e.g. `a`, for `array`, since `b = a array`); anything declared
           earlier (`acc`) is "free". Both still become functor fields (the
           impl can't otherwise know what either concretely is) -- only
           [applied_ty]'s own argument list (what [ty] itself is applied to)
           excludes the free ones, since they aren't part of its type
           constructor at all. [ty] itself may still need *more* type
           parameters than it has tied names for (e.g. `impl showable of
           array`: the trait has no "other" type at all) -- pad with fresh,
           trait-invisible names for the remainder. Kept in sync with
           bin/main.ml's [harvest_dispatch], which reconstructs these exact
           names positionally to know what to instantiate the functor with
           at each dispatch call site. *)
        let tied_count = min (type_arity ty) (List.length other_names) in
        let other_count = List.length other_names in
        let free_names = List.filteri (fun i _ -> i < other_count - tied_count) other_names in
        let tied_names = List.filteri (fun i _ -> i >= other_count - tied_count) other_names in
        let pad_count = max 0 (type_arity ty - List.length tied_names) in
        let pad_names =
          List.init pad_count (fun i -> Printf.sprintf "__elem%d__" (List.length tied_names + i))
        in
        let applied_ty_args = tied_names @ pad_names in
        let all_param_names = free_names @ applied_ty_args in
        let functor_param = "X" in
        let other_ref n =
          if all_param_names = [] then Longident.Lident n else Option.get (Longident.unflatten [ functor_param; n ])
        in
        let applied_ty () =
          Ast_helper.Typ.constr ~loc (Location.mkloc (Longident.Lident ty) loc)
            (List.map (fun n -> Ast_helper.Typ.constr ~loc (Location.mkloc (other_ref n) loc) []) applied_ty_args)
        in
        let type_manifests =
          List.map
            (fun n ->
              let manifest =
                if Some n = self_name then Some (applied_ty ())
                else if List.mem n all_param_names then Some (Ast_helper.Typ.constr ~loc (Location.mkloc (other_ref n) loc) [])
                else None
              in
              Ast_helper.Str.type_ ~loc Recursive [ Ast_helper.Type.mk ~loc ?manifest (Location.mkloc n loc) ])
            abstract_types
        in
        let with_constraint n =
          let manifest = if Some n = self_name then applied_ty () else Ast_helper.Typ.constr ~loc (Location.mkloc (other_ref n) loc) [] in
          Pwith_type (Location.mkloc (Longident.Lident n) loc, Ast_helper.Type.mk ~loc ~manifest (Location.mkloc n loc))
        in
        let module_type =
          match self_name with
          | None -> Ast_helper.Mty.ident ~loc (Location.mkloc (Longident.Lident trait_name) loc)
          | Some self -> Ast_helper.Mty.with_ ~loc (Ast_helper.Mty.ident ~loc (Location.mkloc (Longident.Lident trait_name) loc)) (List.map with_constraint (self :: other_names))
        in
        let methods = match self_name with Some self -> annotate_self_params self methods | None -> methods in
        let body =
          Ast_helper.Mod.constraint_ ~loc
            (Ast_helper.Mod.structure ~loc (type_manifests @ methods))
            module_type
        in
        let mod_expr =
          if all_param_names = [] then body
          else
            let param_sig =
              Ast_helper.Mty.signature ~loc
                (List.map (fun n -> Ast_helper.Sig.type_ ~loc Recursive [ Ast_helper.Type.mk ~loc (Location.mkloc n loc) ]) all_param_names)
            in
            Ast_helper.Mod.functor_ ~loc (Named (Location.mkloc (Some functor_param) loc, param_sig)) body
        in
        [ Ast_helper.Str.module_ ~loc (Ast_helper.Mb.mk (Location.mkloc (Some mod_name) loc) mod_expr) ] }

block:
  | FN; name = IDENT; params = fn_params;
    LBRACE; fbody = block; RBRACE; rest = block
    { mklocalfn (mkloc $startpos $endpos) name params fbody rest }
  | OP; name = CUSTOM; params = fn_params;
    LBRACE; fbody = block; RBRACE; rest = block
    {
      let f_name = "op___" ^ (string_of_int !operator_cnt) ^ "___" in
      incr operator_cnt;
      Hashtbl.add operator_tbl name f_name;
      mklocalfn (mkloc $startpos $endpos) f_name params fbody rest }
  | LET; x = IDENT; EQ; e1 = expr; SEMICOLON; e2 = block
    { let loc = mkloc $startpos $endpos in
      let xloc = mkloc $startpos(x) $endpos(x) in
      Ast_helper.Exp.let_ ~loc Nonrecursive
        [ Ast_helper.Vb.mk (Ast_helper.Pat.var (Location.mkloc x xloc)) e1 ]
        e2 }
  | e1 = expr; SEMICOLON; b = block
    { let loc = mkloc $startpos $endpos in
      Ast_helper.Exp.sequence ~loc e1 b
    }
  | e = expr { e }

body:
  | LBRACE; b = block; RBRACE
      { b }
  | e = expr
      { e }

expr:
  | IF; c = expr; THEN; t = body; ELSE; e = body
    { Ast_helper.Exp.ifthenelse ~loc:(mkloc $startpos $endpos) c t (Some e) }
  | FUN; params = nonempty_list(IDENT); ARROW; e = body
    { mk_fn_expr (mkloc $startpos $endpos) params e }
  | e = expr_bin { e }

expr_bin:
  | e1 = expr_bin; c = CUSTOM; e2 = expr_bin
      {
        let f_name = match Hashtbl.find_opt operator_tbl c with Some f -> f | None -> c in
        let f_ident = mkident (mkloc $startpos(c) $endpos(c)) f_name in
        Ast_helper.Exp.apply ~loc:(mkloc $startpos $endpos) f_ident [(Nolabel, e1); (Nolabel, e2)] 
      }
  | e = tuple { e }

tuple:
  | first = app; COMMA; rest = separated_nonempty_list(COMMA, app)
      { 
        let all = first :: rest in
        Ast_helper.Exp.tuple ~loc:(mkloc $startpos $endpos) (List.map (fun e -> (None, e)) all)
      }
  | e = app { e }
  
indexable:
  | a = indexable; LBRACK; index = expr; RBRACK
      { let f_get_array = mkqident (mkloc $startpos $endpos) "Array.get" in
        Ast_helper.Exp.apply ~loc:(mkloc $startpos $endpos) f_get_array [ (Nolabel, a); (Nolabel, index) ] }
  | a = atom { a }

app:
  | e1 = app; e2 = indexable
    { Ast_helper.Exp.apply ~loc:(mkloc $startpos $endpos) e1 [ (Nolabel, e2) ] }
  | e = indexable { e }

atom:
  | n = INT { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.int n) }
  | s = STRING { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.string s) }
  | f = FLOAT { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.float f) }
  | c = CHAR { Ast_helper.Exp.constant ~loc:(mkloc $startpos $endpos) (Ast_helper.Const.char c) }
  | TRUE { mkbool (mkloc $startpos $endpos) true }
  | FALSE { mkbool (mkloc $startpos $endpos) false }
  | x = IDENT { mkident (mkloc $startpos $endpos) x }
  | q = QIDENT { mkqident (mkloc $startpos $endpos) q }
  | LPAREN; RPAREN { mkunit (mkloc $startpos $endpos) }
  | LPAREN; c = CUSTOM; RPAREN
      { let loc = mkloc $startpos $endpos in
        let f_name = match Hashtbl.find_opt operator_tbl c with Some f -> f | None -> c in
        mkident loc f_name }
  | LPAREN; e = expr; RPAREN { e }
